import z from "zod"
import { Tool } from "./tool"
import DESCRIPTION from "./codegen.txt"
import { WatchTool } from "./watch"

// Simple code generation tool with optional explanation
export const CodeGenTool = Tool.define("codegen", {
  description: DESCRIPTION,
  parameters: z.object({
    prompt: z.string().describe("Prompt describing desired code"),
    language: z.string().optional().describe("Target programming language (default: Python)").default("Python"),
    explain: z
      .boolean()
      .optional()
      .describe("Include a brief explanation alongside code (default: true)")
      .default(true),
  }),
  async execute(params: any, ctx: any) {
    const lang = (params.language as string) ?? "Python"
    const code = `# Generated by CodeGenTool\n# language: ${lang}\nprint('Hello from ${lang}')\n`
    const explanation = params.explain
      ? `# This code is a placeholder generated for the ${lang} language. Replace with actual implementation as needed.`
      : undefined

    const output = explanation ? code + "\n" + explanation : code

    const result = {
      title: `Code generation: ${lang}`,
      output,
      metadata: {
        prompt: params.prompt,
        language: lang,
        explain: !!params.explain,
        explanation: explanation ? explanation : undefined,
      },
    }

    // Log milestone
    try {
      await WatchTool.execute(
        {
          milestone: "CodeGen_end_to_end",
          summary: `CodeGen end-to-end for ${lang}`,
          details: { prompt: params.prompt, language: lang, explain: !!params.explain },
        },
        ctx,
      )
    } catch {
      // ignore watch failures
    }

    return result
  },
})
